server:
  port: 8081
  servlet:
    context-path: /kafka

spring:
  profiles:
    active: dev

kafka:
  topic:
    internalTopicPrefix: _

swagger:
  title: Kafka Manager
  description: Kafka admistration
  version: 1
  swaggerPackage: com.marriott.eeh