server:
  port: 8081
  servlet:
    context-path: /kafka

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kafka:
  topic:
    internalTopicPrefix: _

